# Generated by Django 6.0.2 on 2026-02-18 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPLIED", "Applied"),
                            ("SCREENING", "Screening"),
                            ("TECH", "Tech"),
                            ("ONSITE", "Onsite"),
                            ("OFFER", "Offer"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("job_url", models.URLField(blank=True, null=True)),
                ("applied_date", models.DateTimeField(blank=True, null=True)),
                ("notes_brief", models.TextField(blank=True, null=True)),
                ("jd_url", models.URLField(blank=True, null=True)),
                ("jd_text", models.TextField(blank=True, null=True)),
                ("jd_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="tracker.company",
                    ),
                ),
            ],
        ),
    ]
